function onUpdatePost(elapsed)
    iconP1Modifier = getProperty('healthBar.x') + ((getProperty('healthBar.width') * getProperty('healthBar.percent') * 0.01) + (150 * getProperty('iconP1.scale.x') - 150) / 2 - 26)
    iconP2Modifier = getProperty('healthBar.x') + ((getProperty('healthBar.width') * getProperty('healthBar.percent') * 0.01) - (150 * getProperty('iconP2.scale.x')) / 2 - 26 * 2)
    setProperty('iconP1.x', iconP1Modifier - 90)
    setProperty('iconP1.origin.x', 240)
    setProperty('iconP1.flipX', true)
    setProperty('iconP2.x', iconP2Modifier + 90)
    setProperty('iconP2.origin.x', - 100)
    setProperty('iconP2.flipX', true)
    setProperty('healthBar.flipX', true)
end